NUM_LEDS_HORIZONTAL = 42
NUM_LEDS_VERTICAL = 20
GLOBAL_BRIGHTNESS = 50

NUM_LEDS_TOTAL = 2 * (NUM_LEDS_HORIZONTAL + NUM_LEDS_VERTICAL)
CORNER_LED_POSITIONS = [
    0,
    NUM_LEDS_HORIZONTAL,
    NUM_LEDS_HORIZONTAL + NUM_LEDS_VERTICAL,
    NUM_LEDS_HORIZONTAL * 2 + NUM_LEDS_VERTICAL,
    NUM_LEDS_TOTAL,
]
